# Backend ayarları (Bunlar doğru olmalı)
backend:
  name: git-gateway
  branch: main

# Medya ayarlarını ŞİMDİLİK kaldırıyoruz (hata kaynağı olabilir)
# media_folder: "images/uploads"
# public_folder: "/images/uploads"

# SADECE TEK BİR KOLEKSİYON (Dosya bazlı)
collections:
  - name: "ayarlar"
    label: "Site Ayarları"
    files:
      - file: "content/iletisim-bilgileri.json"
        label: "İletişim Bilgileri"
        name: "iletisim"
        fields:
          - {label: "Adres", name: "adres", widget: "string"}
          - {label: "Telefon", name: "telefon", widget: "string"}
          - {label: "E-posta", name: "email", widget: "string"}